### PR TITLE
Improve doc for exclusions

### PR DESCRIPTION
**Pull request by honnix**
* `excludedClasses` does not exist, so maybe it is legacy
* Added `exclusions` to the example

### CODE REVIEW

**Comment by honnix** [comment]
@skuzzle PTAL, thanks.

BTW, it seems not possible to exclude by class name pattern, such as `com.your.domain.treat.special.**.*IT`. Is that correct? Basically what I want to achieve is banning a package unless the class using that package is named `*IT` wherever in the code base.

**Comment by honnix** [comment]
CI fails due to Java 8 and `-release` flag I think.

**Comment by skuzzle** [comment]
Nice catch. This seems to stem from a naming inconsistency in the code actually.
Can you please change the PR target to the `develop` branch and make the changes in `readme/README.md`? The `README.md` at the toplevel is now auto-generated during release from that template file to fill in the corect version. Also don't mind the failing build. I've actually removed travis in favor of using my own jenkins instance.

Regarding your question: No that is not possible, because right now, wildcards can only match full package/class names. Maybe it would be a good idea to replace the self-implemented matching algorithm with a standard one like AntMatchers or Regex. But that is actually not thaat easy, because of the specificy calculation that is needed for chosing the correct group (see https://github.com/skuzzle/restrict-imports-enforcer-rule#rule-groups)

**Comment by honnix** [comment]
@skuzzle Thanks for the quick reply and all the context and information.

I have now changed the base to `develop`.

Regarding the exclusion package pattern question, yeah I fully understand it would not be easy to replace, so just wanted to confirm.

**Review by skuzzle — APPROVED** [review]

**Comment by skuzzle** [comment]
Merged, but it will only first occur on master when I do a new release. With this new release process, maybe the docs should be separated from the code and moved to GitHub wiki ...

**Comment by honnix** [comment]
@skuzzle Thanks! It's OK we can wait until it appears later. It is not a big deal after all. Regarding moving to wiki, there are cons and pros I guess. A readme page is a lot more accessible than wiki.

**Comment by honnix** [comment]
Thanks for making and maintaining this plugin! _I should have said this earlier._

**Pull request merged**
