### PR TITLE
Add Groovy support

### PR DESCRIPTION
**Pull request by schillingr**
Add support for scanning Groovy source files with the ability to disable.

### CODE REVIEW

**Comment by skuzzle** [comment]
Hi there,

great contribution. I'm happy to include your idea of analyzing groovy files. However I'd like to suggest a more or less _little_ change to your code.
I've already played with the idea of enabling to analyze scala code. Given your approach, when adding more and more languages, we would end up with a whole bunch of further if-statements within the `ImportMatcher`. So I'd rather go with some kind of strategy pattern where
* The `SourceTreeAnalyzer` chooses the correct `ImportMatcher` implementation according to the file extension
* There exists one `ImportMatcher` implementation per supported language
* As in our case both matcher implementations would share like 90% of the code, there probably exists a smart abstraction to avoid duplicated code (like: either use inheritance or composition of helper classes).

What do you think?

I was already thinking about lifting the analysis up to compiled class files. That way we would not have to worry about the actual used JVM language. But this requires bigger changes that I currently have no time planned for.

**Comment by schillingr** [comment]
Hi Simon,

Thanks for taking the time to put together such a thoughtful response. I
apologize for my delay on getting back to you.

I'll look into implementing your suggestions and update the pull request.

As for moving the analysis to compiled classes I think that does provide
the benefit of not having to parse the language, however you might
introduce some other challenges since compiled code is composed of more
than just the source file being parsed today (think AST transformations).

Take care.

**Comment by skuzzle** [comment]
Great, I'm looking forward to see the result. Do not hesitate to ask if you encounter any trouble while implementing this.
I have two ideas/suggestions up front: 
1. A good abstraction could likely be an interface that is supposed to just collect the import statements found within a source file, say `ImportCollector`. Then we would have multiple implementations like `JavaImportCollector`, `GroovyImportCollector`, ... you get the point. That way we can easily separate the tasks of finding the import statements (which is language/source file specific) from matching them against the banned import definitions. The latter would simply operate on the list provided by the collector and does not need to know from which kind of source file the imports originated.
2. I think we do not need an extra flag like `enableGroovySupport`. It is probably fine if we just work on any file we encounter within the source folder(s) and for which we have an `ImportMatcher` implementation (or `...Collector` of you follow my previous idea)

**Comment by skuzzle** [comment]
That looks awesome. Like 95% the way I would have solved that 👍 
I'll merge this PR and will make some minor changes before releasing it into the wild. Thanks again for this great enhancement!

**Comment by skuzzle** [comment]
FYI: I released this with some minor changes as 0.15.0

**Pull request merged**
